# Generated by Django 3.1.1 on 2020-09-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSBazaarCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
    ]
