# Generated by Django 3.1.1 on 2020-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSBazaarCore', '0002_auto_20200926_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonuser',
            fields=[
                ('phone_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
