# Generated by Django 3.1.1 on 2020-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSBazaarCore', '0003_nonuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
