# Generated by Django 3.1.1 on 2020-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSBazaarCore', '0004_scratch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('upload', models.ImageField(upload_to='uploads/')),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
