# Generated by Django 3.1.1 on 2020-09-27 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SMSBazaarCore', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_ph_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
