# Generated by Django 3.1.1 on 2020-09-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSBazaarCore', '0006_item_vendor_ph_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='price',
        ),
    ]
